name: anantata
description: "Anantata Career Coach - AI-powered career development"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # Utilities
  intl: ^0.19.0
  http: ^1.2.0

  # Storage
  shared_preferences: ^2.2.2

  # AI
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env